<template>
  <Loading :active="isLoading"
           :is-full-page="fullPage">
           <!--樣式包進 loading 元件內-->
           <div class="loadingio-spinner-magnify-ki0t54cccsf"><div class="ldio-gafo7wcq9r4">
          <div><div><div></div><div></div></div></div>
          </div></div>
          <!--樣式包進 loading 元件內-->
  </Loading>
  <section class="section-error">
    <div class="container">
      <div class="content">
        <p class="title">親，你要看的頁面好像不在呢</p>
        <p>趕緊返回首頁選定基金淘金去 </p>
        <router-link to="/" class="btn-back">返回首頁</router-link>
      </div>
    </div>
  </section>
</template>
<script>
export default {
  data () {
    return {
      isLoading: true,
      fullPage: true
    }
  },
  mounted () {
    setTimeout(() => {
      this.isLoading = false
    }, 2000)
  }
}
</script>
<style scoped>
@keyframes ldio-gafo7wcq9r4 {
  0%    { transform: translate(2px,2px) }
  33.33% { transform: translate(102px,2px) }
  66.66% { transform: translate(42px,102px) }
  100%    { transform: translate(2px,2px) }
}
.ldio-gafo7wcq9r4 > div {
  transform: scale(0.8);
  transform-origin: 100px 100px;
}

.ldio-gafo7wcq9r4 > div > div {
  animation: ldio-gafo7wcq9r4 2.6315789473684212s linear infinite;
  position: absolute
}

.ldio-gafo7wcq9r4 > div > div div:nth-child(1) {
  width: 72px;
  height: 72px;
  border-radius: 50%;
  border: 12px solid #71c2cc;
  background: transparent;
}

.ldio-gafo7wcq9r4 > div > div div:nth-child(2) {
  width: 17px;
  height:  51px;
  transform: rotate(-45deg);
  background: #71c2cc;
  border-radius: 0 0 8px 8px;
  position: absolute;
  top: 68px;
  left: 85px
}
.loadingio-spinner-magnify-ki0t54cccsf {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-gafo7wcq9r4 {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-gafo7wcq9r4 div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>
