<template>
  <section class="section-bannerOrder">
    <Loading :active="isLoading">
           <!-- 樣式包進 loading 元件內-->
           <div class="loadingio-spinner-magnify-ki0t54cccsf"><div class="ldio-gafo7wcq9r4">
          <div><div><div></div><div></div></div></div>
          </div></div>
          <!-- 樣式包進 loading 元件內 -->
    </Loading>
    <div class="container">
      <div class="content">
        <p>投資需遵守紀律，持之以恆獲得豐厚的報酬果實</p>
      </div>
    </div>
  </section>
  <Progress :currentProgress="currentProgress"></Progress>
  <section class="section-order">
    <div class="container">
      <div class="block-order">
        <div class="content">
          <div class="apply-tr">
            <div class="apply-th">專案優惠</div>
            <div class="apply-td">{{orderData.project}}</div>
          </div>
          <div class="apply-tr">
            <div class="apply-th">基金名</div>
            <div class="apply-td">{{orderData.code}} {{orderData.fund}}</div>
          </div>
          <div class="apply-tr">
            <div class="apply-th">基金申購幣別</div>
            <div class="apply-td">{{orderData.currency}}</div>
          </div>
          <div class="apply-tr">
            <div class="apply-th">日期</div>
            <div class="apply-td">{{orderData.date}}</div>
          </div>
          <div class="apply-tr">
            <div class="apply-th">扣款帳號</div>
            <div class="apply-td">
              {{orderData.account}}
              <span class="remark">目前餘額： {{ orderData.currency === '台幣' ?
                `$NT ${$filters.toCurrency(orderData.availableCash)}` :
                `USD ${$filters.toCurrency(orderData.availableCash)}`}}</span>
            </div>
          </div>
          <div class="apply-tr">
            <div class="apply-th">申購金額</div>
            <div class="apply-td">
              {{ orderData.currency === '台幣' ? `$NT ${$filters.toCurrency(orderData.amountNt)}` :
               `USD ${$filters.toCurrency(orderData.amountUsd)}` }}
            </div>
          </div>
          <div class="block-btn">
            <div class="btn" @click="backHome">回首頁</div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>
<script>
import Progress from '@/components/Progress.vue'
import localStorageOrder from '@/methods/localStorage-order.js'

export default {
  data () {
    return {
      currentProgress: this.$route.name,
      orderData: this.getOrder(),
      isLoading: false
    }
  },
  components: {
    Progress
  },
  mixins: [localStorageOrder],
  methods: {
    backHome () {
      setTimeout(() => {
        this.isLoading = true
      }, 1000)
      setTimeout(() => {
        this.$router.push('/')
      }, 2500)
    }
  }
}
</script>
<style scoped>
@keyframes ldio-gafo7wcq9r4 {
  0% {
    transform: translate(2px, 2px);
  }
  33.33% {
    transform: translate(102px, 2px);
  }
  66.66% {
    transform: translate(42px, 102px);
  }
  100% {
    transform: translate(2px, 2px);
  }
}
.ldio-gafo7wcq9r4 > div {
  transform: scale(0.8);
  transform-origin: 100px 100px;
}

.ldio-gafo7wcq9r4 > div > div {
  animation: ldio-gafo7wcq9r4 2.6315789473684212s linear infinite;
  position: absolute;
}

.ldio-gafo7wcq9r4 > div > div div:nth-child(1) {
  width: 72px;
  height: 72px;
  border-radius: 50%;
  border: 12px solid #aaa;
  background: transparent;
}

.ldio-gafo7wcq9r4 > div > div div:nth-child(2) {
  width: 17px;
  height: 51px;
  transform: rotate(-45deg);
  background: #aaa;
  border-radius: 0 0 8px 8px;
  position: absolute;
  top: 68px;
  left: 85px;
}
.loadingio-spinner-magnify-ki0t54cccsf {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-gafo7wcq9r4 {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-gafo7wcq9r4 div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
